<div class="box">
	<img src="<?php echo $this->getSkinUrl('images/bolfeed/logo.png'); ?>" style="float:left;margin: 18px 30px 0 10px;"/>
	<p>
		Bolfeed - Plaats, beheer en analyseer je producten en verkopen automatisch op bol.com Plaza.<br />
		Bolfeed is specifiek gemaakt voor alle bol.com verkopers en marketeers die resultaatgericht willen verkopen op bol.com in Nederland en België.
	</p>

	<p><strong>support</strong><br/>
	Bel of mail het Bolfeed team, we helpen je graag verder! support@bolfeed.nl - een beller is sneller via 088 4800888.<br/>	
	Voor documentatie en ondersteuning zie <a href="http://www.bolfeed.nl" target="_blank">bolfeed.nl</a></p>
    <div style="clear:both;width:1px;height:1px;font-size:1px;overflow:hidden;">&nbsp;</div>
</div>
 